# ConfigMap to expose configuration related to backend application
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf # name of configMap
data:
  server-uri: a5ce1b82990dd11ea86af02e678086ab-63077834.us-west-2.elb.amazonaws.com # enternal ip of backend application 'Service'
